spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    token:
      access_expiration: ${JWT_ACCESS_EXPIRATION}
      refresh_expiration: ${JWT_REFRESH_EXPIRATION}

springdoc:
  api-docs:
    enabled: true                         # OpenAPI 문서 활성화
  swagger-ui:
    enabled: true                         # UI 활성화
    path: /swagger-ui.html                # 기본 접속 경로
  override-with-generic-response: false   # 응답 형식 오버라이드 금지

api:
  portOne:
    token: ${PORTONE_TOKEN}
    storeId: ${PORTONE_STORE_ID}
    host: ${PORTONE_HOST}

server:
  port: 8080

management:
  server:
    port: 9091  # Prometheus, Health Check 등 관리용 포트
  endpoints:
    web:
      exposure:
        include: "prometheus,health"